Repository Knackie/algorithmshacktoberfest2022, pull requests merged in 2022-10, with the labels that each got.

#231 Added ar-hsrt.java
  algorithms/ar-hsrt/ar-hsrt.java
Labels: hacktoberfest, hacktoberfest-accepted

#235 Create heapsort.cpp
  algorithms/Sorting_Algorithms/C++/heapsort.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#243 Fixed link
  README.md
Labels: hacktoberfest, hacktoberfest-accepted

#239 Update Selection Sort.cpp
  algorithms/Sorting_Algorithms/C++/Selection Sort.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#233 code of seive of eratosthenes in java
  README.md
  algorithms/ar-soer/seive.java
Labels: hacktoberfest, hacktoberfest-accepted

#241 Update heapsort.cpp
  algorithms/Sorting_Algorithms/C++/heapsort.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#248 Added bubblesort in python2 and updated readme
  README.md
  algorithms/ar-bsrt/python2/bubblesort.py
  algorithms/ar-isrt/python2/insertionsort.py
Labels: hacktoberfest, hacktoberfest-accepted

#251 Created boyermoore.cpp and updated the README
  README.md
  algorithms/ar-bm/boyermoree.cpp
  algorithms/boyermoree.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#230 Create Binary Sort in C#
  algorithms/ar-bsrh/Binary Sort in C#
Labels: hacktoberfest, hacktoberfest-accepted

#244 added bogosort.java
  algorithms/ar-bogosort/C++/C++/bogosort.cpp
  algorithms/ar-bogosort/C++/Java/bogosort.java
Labels: hacktoberfest, hacktoberfest-accepted

#238 Update Merge_sort.cpp
  algorithms/Sorting_Algorithms/C++/Merge_sort.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#254 feat : Bogosort on Typescript
  README.md
  algorithms/ar-bogosort/typescript/bogosort.ts
Labels: hacktoberfest, hacktoberfest-accepted

#256 Added sieve of eratosthenes in python2 and updated readme.
  README.md
  algorithms/ar-soer/python2/sieveoferatosthenes.py
Labels: hacktoberfest, hacktoberfest-accepted

#259 Bottom view of Binary Tree
  algorithms/Bottom View Of Binary Tree.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#258 Pigeon Hole Sort
  algorithms/PigeonHole Sort.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#257 K-Nearest Neighbors Algorithm in C++
  algorithms/K-NN Algorithm.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#253 Created Dijsktra Algorithm Program
  algorithms/Dijkstra’s shortest path algorithm.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#262 Added C implementation of KMP algorithm.
  README.md
  algorithms/ar-kmp/c/ar_kmp
  algorithms/ar-kmp/c/ar_kmp.c
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#263 added rightview.cpp
  README.md
  algorithms/rightview.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#225 Searching
  algorithms/Searching/Search_In_a_2D_Matrix.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#265 Fixed README.
  README.md
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#269 ar.hsrt
  README.md
  algorithms/ar-hsrt/C/ar.hsrt.c
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#267 Add: Z function in Java and updated Readme
  DSA/string/ZAlgorithm.java
  README.md
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#264 Added Count Sort in python3
  README.md
  algorithms/ar-csrt/Python/Count_Sort.py
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#275 Create NaiveSearch.java
  algorithms/ar-nsrh/NaiveSearch.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#247 Create ar-qsrt.dart
  README.md
  algorithms/ar-qsrt/Dart/ar-qsrt.dart
Labels: hacktoberfest, hacktoberfest-accepted

#278 Added Shell sort in C Language
  README.md
  algorithms/ar-shsrt/c/ar-shsrt.c
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#280 Create Middle Element of Linked List
  DSA/linkedList/Middle Element of Linked List
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#277 Added python3 implementation of KMP algorithm.
  README.md
  algorithms/ar-kmp/c/ar_kmp
  algorithms/ar-kmp/python3/ar_kmp.py
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#284 Added Bogosort algorithms
  README.md
  algorithms/ar-bogosort/C++/Java/bogosort.java
  algorithms/ar-bogosort/C++/bogosort.cpp
  algorithms/ar-bogosort/elixir/bogosort.exs
  algorithms/ar-bogosort/java/Bogosort.java
  algorithms/ar-bogosort/javascript/bogosort.js
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#283 Added the counting sort algorithm in javascript
  README.md
  algorithms/ar-csrt/Javascript/count_sort.js
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#285 added mergesort in python2 and edited readme.
  README.md
  algorithms/ar-msrt/python2/mergesort.py
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#281 Added bfs.c
  README.md
  algorithms/gr-bfsrh/gr-bfsrh.c
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#286 Create ar-qsrt.c
  README.md
  algorithms/ar-qsrt/C/ar-qsrt.c
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#291 added coin change problem javascript script
  README.md
  algorithms/ar-cochprb/Javascript/coin_change.js
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#295 Added coinchange in python2 and updated readme
  README.md
  algorithms/ar-cochprb/python2/coinchange.py
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#294 Added Jump Search algorithm and Quick Sort algorithm
  algorithms/Searching/JumpSearch.cpp
  algorithms/Sorting_Algorithms/C++/QuickSort.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#249 Added Heap sort in C language
  algorithms/ar-hsrt/ar-hsrt.c
Labels: hacktoberfest, hacktoberfest-accepted

#250 Create Longest-Palindromic-Substring.py
  algorithms/Longest-Palindromic-Substring.py
Labels: hacktoberfest, hacktoberfest-accepted

#300 Added LIS algorithm and Updated readme
  README.md
  algorithms/ar-lis/Java/ar-lis.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#299 Added count sort algorithm in the ar-crt folder
  algorithms/ar-csrt/Python3/count_sort.py
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#298 Added Evaluate_postfix.c algorithm in the ar-pstfix folder.
  README.md
  algorithms/ar-pstfix/Evaluate_Postfix.c
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#297 Create mexp.py
  README.md
  algorithms/ar-mexp/Python/mexp.py
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#305 Added Algorithms
  README.md
  algorithms/MinMax.cpp
  algorithms/Searching/A_star.cpp
  algorithms/Searching/Best_First _Search.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#304 Counting Sort Algorithm with Python3 #234
  README.md
  algorithms/ar-csrt/Python3/Count Sort.py
  algorithms/ar-csrt/Python3/Implementation Of counting Sort Algorithm in Python.py
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#306 Added count sort in Python 3 #272
  algorithms/ar-csrt/Python3/#Main Algorithm For Count Sort in Python.py
  algorithms/ar-csrt/Python3/Counting_Sort.py
Labels: good first issue, hacktoberfest, hacktoberfest-2022

#308 Added mexp.c into good folder
  README.md
  algorithms/ar-mexp/mexp.c
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#311 added README.md for DSA and algorithms folder
  CONTRIBUTING.md
  DSA/README.md
  algorithms/README.md
Labels: documentation, good first issue, hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#312 Added Boyer Moore algorithm
  README.md
  algorithms/ar-bm/Java/BoyerMoore.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#315 Updated README.md
  README.md
Labels: documentation, hacktoberfest-accepted, hacktoberfest-2022

#314 Added ar-binsrt.cs to good folder
  README.md
  algorithms/ar-binsrt/C#/ar-binsrt.cs
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#318 Added ar-prfac in PHP
  README.md
  algorithms/ar-prfac/PHP/prime-factors.php
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#323 Create PigeonHoleSort.c
  algorithms/ar-pgsrt/PigeonHoleSort.c
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#324 Code lalit007 patch 1
  DSA/queue.cpp
  README.md
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#326 DP Code
  DSA/DP/LongestPalindromicSubstring.cpp
  DSA/DP/count_the_subset_of_given_diff.cpp
  DSA/DP/lcs.cpp
  DSA/DP/longest palindromic substring.cpp
  DSA/DP/longest_common_subsequence.cpp
  DSA/DP/longest_increasing_subsequence.cpp
  DSA/DP/longest_palindromic_subsequenece.cpp
  DSA/DP/minimum_sum_partition.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#328 Added CPU scheduling algorithms #279
  README.md
  algorithms/CPUScheduler.java
  algorithms/ar-Cpuschpr
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#336 Added Segment Tree with Lazy Propagation
  DSA/segment-tree/segtree.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#327 added bfs search using javascript
  README.md
  algorithms/gr-bfsrh/bfs.js
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#331 Added Exponentiation by Squaring algorithm in the arr-expsq/Python folder
  README.md
  algorithms/ar-expsq/Python3/expsq.py
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#329 Update README.md
  README.md
Labels: documentation, hacktoberfest, hacktoberfest-2022

#330 Added left view of binary tree in C language
  algorithms/ar-lvwbintr/C/leftviewbt.c
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#341 added dfs search algorithm in javascript
  README.md
  algorithms/gr-dfsrh/dfs.js
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#333 added linked list cpp
  algorithms/100-same-tree.cpp
  algorithms/Basic_Cpp_Template.cpp
  algorithms/BubbleSort.cpp
  algorithms/Flip Binary Equivalent Binary Tree.cpp
  algorithms/KMP.cpp
  algorithms/Mergesort.cpp
  algorithms/binarySearch.cpp
  algorithms/binary_exponentiation.cpp
  algorithms/exponentialSearch.cpp
  algorithms/interpolationSearch.cpp
  algorithms/jumpSearch.cpp
  algorithms/linearSearching.cpp
  algorithms/linkList.cpp
  algorithms/merge-two-sorted-lists.cpp
  algorithms/reversing_linkedlist.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#339 Add Heap sorting also update the readme file
  DSA/sorting/HeapSort.java
  README.md
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#338 Added bin sort in js
  README.md
  algorithms/ar-binsrt/javascript/binSort.js
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#343 Added n_queens Problem in cpp
  algorithms/n_queens.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#344 Updated README.md
  README.md
Labels: documentation, hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#345 Added sliding Window algos and removed errors from selection sort
  algorithms/ar-ssrt/java/SelectionSort.java
  algorithms/slidingWindow/maxSum.cpp
  algorithms/slidingWindow/slidingWindowMedian.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#347 Added lcs algorithm in javascript
  README.md
  algorithms/ar-lcs/javascript/ar-lcs.js
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#348 Create Zig_Zag_Traversal.cpp
  README.md
  algorithms/Zig_Zag_Traversal.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#349 Added Topological Sort
  README.md
  algorithms/Topological- Sort/toposort.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#350 Added Java solution for Largest Sum for Continuous Subarray
  README.md
  algorithms/ar-lscsa/Java/lscsa.java
Labels: hacktoberfest 2020, hacktoberfest-accepted, hacktoberfest-2022

#351 Added brute force algo examples in cpp
  DSA/brute force example/BuyAShovel.cpp
  DSA/brute force example/DoNotBeDistracted.cpp
  DSA/brute force example/SpyDetected.cpp
  README.md
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#355 added kadane's algorithm in javascript
  DSA/sorting/Heapsort.java
  README.md
  algorithms/ar-kdn/javascript/ar-kdn.js
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#356 Added Kadane's Algorithm in Python3
  README.md
  algorithms/ar-kdn/python/kdn.py
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#358 Greedy algorithms
  README.md
  algorithms/greedy/greedy.py
Labels: hacktoberfest, hacktoberfest-accepted

#359 Contribute Ar qsel
  README.md
  algorithms/ar-qsel/ar-qsel.cs
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#364 Added Insertion in LinkedList at Different Position in DSA Folder
  DSA/linkedList/insertionInDiffPosinLL.cpp
  README.md
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#366 greedy.cpp added
  README.md
  algorithms/greedy/greedy.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#380 matrix_chain_multiplication algorithm
  algorithms/matrix_chain.c
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#376 Contribute Ar isrt.
  algorithms/ar-isrt/Insertion Sort.c
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#375 disk scheduling in c program added
  README.md
  algorithms/scheduling.c
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#368 Added DNF Algo
  algorithms/Sorting_Algorithms/C++/DNFAlgo.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#352 Create prims.c
  README.md
  algorithms/prims.c
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#385 Updated readme file regarding issue#320
  README.md
Labels: documentation, hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#389 Added Amazon OA questions
  README.md
  algorithms/AmazonOA.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#388 Added counting sort algorithm
  DSA/sorting/counting_sort.py
  README.md
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#384 Create CountingSort,java
  DSA/sorting/CountingSort,java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#372 Added Floyd's Cylce Detection regarding issue #320
  DSA/linkedList/FloydCycleDetection.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#363 Added Fenwick Tree in C++ for #362
  DSA/FenwickTree/fenwicktree.cpp
  README.md
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#397 #378 . Added solution to DO NOT BE DISTRACTED [codeforces problem] in JAVA.
  DSA/brute force example/DoNotBeDistracted.java
  README.md
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#396 Added Python 3 code for Bogosort in algorithms/ar-bogosort
  README.md
  algorithms/ar-bogosort/python/bogosort.py
Labels: hacktoberfest, hacktoberfest-accepted

#393 Added short shell.js algorithm
  README.md
  algorithms/ar-shsrt/js/ar-shsrt.js
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#394 Added Bogosort using Python
  README.md
  algorithms/sorting-py/bogosort.py
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#395 Added Breadth First Search Algorithm in C#
  README.md
  algorithms/gr-bfsrh/bfs.cs
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#400 Updated algorithms folder.
  README.md
  algorithms/gr-dfsrh/dfs.java
Labels: hacktoberfest, hacktoberfest-accepted

#403 Added MIN Max Algo, C
  README.md
  algorithms/ar-minmax/Min Max.c
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#402 Bucket Sort
  DSA/sorting/bucket_sort.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#405 Update README.md
  README.md
Labels: documentation, good first issue, hacktoberfest-accepted, hacktoberfest-2022

#414 Created Depth First Search.cs
  README.md
  algorithms/gr-dfsrh/dfsrh.cs
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#415 Updated README.md
  README.md
Labels: hacktoberfest-accepted

#413 Search Element in Matrix.c
  DSA/matrix/Search Element in Matrix.c
  README.md
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#408 added radix sort in python
  algorithms/ar-radsrt/Python/radixsort.py
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#409 Added Prim's algorithm in javascript
  README.md
  algorithms/gr-prims/javascript/isPrime.js
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#407 Added Odd Even Linked List Code
  DSA/linkedList/Odd Even Linked List
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#401 Added Longest Increasing Subsequence
  algorithms/Longest_Increasing_Subsequence.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#390 CPU sch algorithms added
  algorithms/CPU_scheduling.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#418 Added Prims algorithm in the gr-prims folder.
  README.md
  algorithms/gr-prims/JAVA/Prims.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#419 Bucket Sort in C
  README.md
  algorithms/bucket_sort/bucket_sort.c
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#423 Added sleepsort in DSA folder
  DSA/sorting/sleep-sort.c
  README.md
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#422 Added z function in python3
  README.md
  algorithms/ar-zfnc/C++/z_function.cpp
  algorithms/ar-zfnc/Python3/test_z_function.py
  algorithms/ar-zfnc/Python3/z_function.py
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#420 Added Topological Sort Algorithm in Python 3
  README.md
  algorithms/Topological- Sort/topologicalSort.py
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#417 Updated folder Sorting_Algorithms.
  algorithms/Sorting_Algorithms/C++/C/Selection Sort.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#436 PIGEONHOLE SORT IN C++
  algorithms/ar-pgsrt/pigeonholesort.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#437 Cyclic sort
  DSA/sorting/cyclicSort.cpp
  README.md
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#439 Create bucketsort.java
  DSA/sorting/bucketsort.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#440 Update README.md
  README.md
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#431 Added Evaluate Postfix Expression using python3
  README.md
  algorithms/ar-pstfix/C++/Evaluate_Postfix.cpp
  algorithms/ar-pstfix/C/Evaluate_Postfix.c
  algorithms/ar-pstfix/Python3/evaluate_postfix.py
  algorithms/ar-pstfix/Python3/test_evaluate_postfix.py
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#441 Added Binary Search in JS
  README.md
  algorithms/Searching/BinarySearch.js
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#442 added ar-prfac in JS | Readme updated
  README.md
  algorithms/ar-prfac/JS/prime_factor.js
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#444 Update README.md
  README.md
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#445 Added Bit Manipulation
  DSA/Bit Manipulation/Clear_Bit.c++
  DSA/Bit Manipulation/Get_Bit.c++
  DSA/Bit Manipulation/Set_Bit.c++
  DSA/Bit Manipulation/Update_Bit.c++
Labels: hacktoberfest, hacktoberfest-accepted

#447 added bucket_sort in js
  README.md
  algorithms/bucket_sort/bucket_sort.js
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#452 Implement sleep sort in c
  README.md
  algorithms/ar-slpsrt/c/ar-slpsrt.c
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#450 Create lcsa.c
  algorithms/ar-lscsa/C/lcsa.c
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#454 Create Counting_sort.cpp
  algorithms/Sorting_Algorithms/C++/Counting_sort.cpp
Labels: hacktoberfest, hacktoberfest-2022
